SELECT *
FROM "DB"."SCHEMA"."table1"
WHERE LOWER(text_col) LIKE '%connect with%'
    OR LOWER(text_col) LIKE '%communicate with%'
    OR LOWER(text_col) LIKE '%mailing list%'
    OR LOWER(text_col) LIKE '%send email%'
    OR LOWER(text_col) LIKE '%over email%'
    OR LOWER(text_col) LIKE '%through emails%'
    OR LOWER(text_col) LIKE '%messaging%'
    OR LOWER(text_col) LIKE '%through text messages%'
    OR LOWER(text_col) LIKE '%text messages%'
    OR LOWER(text_col) LIKE '%via email%'
    OR LOWER(text_col) LIKE '%live chat%'
    OR LOWER(text_col) LIKE '%bulk emails%'
    OR LOWER(text_col) LIKE '%email notifications%'
    OR LOWER(text_col) LIKE '%newsletters%'
    OR LOWER(text_col) LIKE '%sms%'
    OR LOWER(text_col) LIKE '%email to%'
    OR LOWER(text_col) LIKE '%receive a message%'
    OR LOWER(text_col) LIKE '%commentary%'
    OR LOWER(text_col) LIKE '%chat%'
    OR LOWER(text_col) LIKE '%meet with%'
    OR LOWER(text_col) LIKE '%via sms%'
    OR LOWER(text_col) LIKE '%secure communication%'
    OR LOWER(text_col) LIKE '%send%'
    OR LOWER(text_col) LIKE '%to an individual%'
    OR LOWER(text_col) LIKE '%communicate%'
    OR LOWER(text_col) LIKE '%email%';
