– Step 1: Create a base table with all unique IDs from the primary dataset
WITH base_table AS (
SELECT DISTINCT
CAST(IDN_EON AS VARCHAR) AS IDN_EON,
‘ITAT’ AS source_table
FROM “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_ITAT_SYS_Active_Owning_Filter”
WHERE IDN_EON IS NOT NULL
),

– Step 2: Collect all unique IDs from multiple source tables
all_ids AS (
SELECT DISTINCT
CAST(IDN_EON AS VARCHAR) AS IDN_EON,
‘ITAT’ AS source_table
FROM “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_ITAT_SYS_prepared_filtered”
WHERE IDN_EON IS NOT NULL

```
UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'PrivacyQ' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_PrivacyQ_for_ITSO_Att_prepared_filtered_filtered"
WHERE IDN_EON IS NOT NULL

UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'SOURCE_CODE' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_DLM_WORM"
WHERE IDN_EON IS NOT NULL

UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'MYSDM' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_MYSDM_Detections_for_Bulk_Email_prepared_filtered"
WHERE IDN_EON IS NOT NULL

UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'DLM' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_DLM_Plan_Responses_filtered2"
WHERE IDN_EON IS NOT NULL

UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'EPR' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_epr_filtered"
WHERE IDN_EON IS NOT NULL
```

),

– Step 3: For each unique ID, combine all the sources that flagged it
aggregated AS (
SELECT
IDN_EON,
LISTAGG(source_table, ’, ’) WITHIN GROUP (ORDER BY source_table) AS DETECTION_TYPE
FROM all_ids
GROUP BY IDN_EON
),

– Step 4: Detect specific keywords and capabilities for each ID
keyword_detection AS (
SELECT
base_table.IDN_EON AS EON_ID,
MAX(t.TXT_DSPLY_LABEL) AS GRN,
MAX(NME_TAI_ASSET_DSPLY) AS APP_NAME,
a.detection_type AS DETECTION_TYPE,
‘YES’ AS ECOMMS_CAPABILITY,
MAX(t.TXT_RSRC_DESC) AS TXT_RSRC_DESC,
MAX(t.TXT_APPL_DESC) AS TXT_APPL_DESC,
CASE
WHEN MAX(w.Email) = ‘x’ THEN ‘YES’
WHEN MAX(TXT_RSRC_CAP_DESC) ILIKE ‘%b2b email%’ THEN ‘YES’
WHEN POSITION(‘mailing list’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘send email’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘over email’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘through emails’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘via email’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘bulk emails’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘email notifications’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘save-receipts’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘email to’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘send to’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘e-comm’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘e-comms’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘ecomm’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘ecomms’ IN MAX(t.TXT_RSRC_DESC)) > 0 THEN ‘YES’
WHEN POSITION(‘mailing list’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘Email’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘email’ IN d.TXT_DATA_LIFECYCL_MANG_ANSW) > 0 THEN ‘YES’
ELSE MAX(w.Email)
END AS EMAIL,
CASE
WHEN MAX(w.Comments) = ‘x’ THEN ‘YES’
WHEN POSITION(‘commentary’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘comment’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘Comments’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘comments’ IN MAX(t.TXT_RSRC_DESC)) > 0 THEN ‘YES’
ELSE MAX(w.Comments)
END AS COMMENTS,
CASE
WHEN MAX(w.Chat) = ‘x’ THEN ‘YES’
WHEN POSITION(‘live chat’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘Chat’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘chat’ IN MAX(t.TXT_RSRC_DESC)) > 0 THEN ‘YES’
ELSE MAX(w.Chat)
END AS CHAT,
CASE
WHEN MAX(w.SMS) = ‘x’ THEN ‘YES’
WHEN POSITION(‘through text messages’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘text messages’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘sms’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘via sms’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘text’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘SMS’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘SMS’ IN MAX(t.TXT_RSRC_DESC)) > 0 THEN ‘YES’
ELSE MAX(w.SMS)
END AS SMS,
CASE
WHEN POSITION(‘Voice’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 THEN ‘YES’
ELSE ‘No’
END AS VOICE
FROM base_table
LEFT JOIN aggregated a ON base_table.IDN_EON = a.IDN_EON
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_dlm_worm” w
ON base_table.IDN_EON = CAST(w.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_DLM_Plan_Responses_filtered2” d
ON base_table.IDN_EON = CAST(d.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_PrivacyQ_for_ITSO_Att_prepared_filtered_filtered” p
ON base_table.IDN_EON = CAST(p.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_MYSDM_Detections_for_Bulk_Email_prepared_filtered” m
ON base_table.IDN_EON = CAST(m.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_epr_filtered” e
ON base_table.IDN_EON = CAST(e.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_ITAT_SYS_Active_Owning_Filter” t
ON base_table.IDN_EON = CAST(t.IDN_EON AS VARCHAR)
WHERE a.detection_type IS NOT NULL AND a.detection_type <> ‘ITAT-SYS’
GROUP BY base_table.IDN_EON, a.detection_type, d.TXT_DATA_LIFECYCL_MANG_ANSW, d.TXT_DATA_LIFECYCL_MANG_QSTN
),

– Step 5: Aggregate to one row per IDN_EON with merged values
final_output AS (
SELECT
EON_ID,
DETECTION_TYPE,
MAX(GRN) AS GRN,
MAX(APP_NAME) AS APP_NAME,
MAX(ECOMMS_CAPABILITY) AS ECOMMS_CAPABILITY,
– Use MAX to merge YES values, keeping YES over other values
MAX(CASE WHEN EMAIL = ‘YES’ THEN ‘YES’ ELSE EMAIL END) AS EMAIL,
MAX(CASE WHEN COMMENTS = ‘YES’ THEN ‘YES’ ELSE COMMENTS END) AS COMMENTS,
MAX(CASE WHEN CHAT = ‘YES’ THEN ‘YES’ ELSE CHAT END) AS CHAT,
MAX(CASE WHEN SMS = ‘YES’ THEN ‘YES’ ELSE SMS END) AS SMS,
MAX(CASE WHEN VOICE = ‘YES’ THEN ‘YES’ ELSE VOICE END) AS VOICE
FROM keyword_detection
GROUP BY EON_ID, DETECTION_TYPE
)

– Step 6: Add the ONBOARDED_TO_ECOMMS_ARCHIVE column based on risk B table
SELECT
EON_ID,
DETECTION_TYPE,
GRN,
APP_NAME,
ECOMMS_CAPABILITY,
EMAIL,
COMMENTS,
CHAT,
SMS,
VOICE,
CASE
WHEN NOT EXISTS (
SELECT 1
FROM “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_Risk_B_Output_2_prepared” risk_b
WHERE risk_b.IDN_EON = keyword_detection.EON_ID
) THEN
CASE
WHEN LOWER(DETECTION_TYPE) NOT LIKE ‘%dlm_plan_responses%’ THEN ‘A,B’
ELSE ‘B’
END
ELSE
CASE
WHEN LOWER(DETECTION_TYPE) NOT LIKE ‘%dlm_plan_responses%’ THEN ‘A’
ELSE NULL
END
END AS SUB_RISK,
CASE
WHEN EXISTS (
SELECT 1
FROM “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_Risk_B_Output_2_prepared” risk_b
WHERE risk_b.IDN_EON = keyword_detection.EON_ID
) THEN ‘YES’
ELSE ‘No’
END AS ONBOARDED_TO_ECOMMS_ARCHIVE
FROM final_output
ORDER BY EON_ID;