– Step 1: Create a base table with all unique IDs from the primary dataset
WITH base_table AS (
SELECT DISTINCT
CAST(IDN_EON AS VARCHAR) AS IDN_EON,
‘ITAT’ AS source_table
FROM “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_ITAT_SYS_Active_Owning_Filter”
WHERE IDN_EON IS NOT NULL
),

– Step 2: Collect all unique IDs from multiple source tables
all_ids AS (
SELECT DISTINCT
CAST(IDN_EON AS VARCHAR) AS IDN_EON,
‘ITAT’ AS source_table
FROM “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_ITAT_SYS_prepared_filtered”
WHERE IDN_EON IS NOT NULL

```
UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'PrivacyQ' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_PrivacyQ_for_ITSO_Att_prepared_filtered_filtered"
WHERE IDN_EON IS NOT NULL

UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'SOURCE_CODE' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_DLM_WORM"
WHERE IDN_EON IS NOT NULL

UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'MYSDM' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_MYSDM_Detections_for_Bulk_Email_prepared_filtered"
WHERE IDN_EON IS NOT NULL

UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'DLM' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_DLM_Plan_Responses_filtered2"
WHERE IDN_EON IS NOT NULL

UNION ALL

SELECT DISTINCT
    CAST(IDN_EON AS VARCHAR) AS IDN_EON,
    'EPR' AS source_table
FROM "LH_SND_DB"."WMCLOUD_PRJ166"."MAEVEPERSONAL_epr_filtered"
WHERE IDN_EON IS NOT NULL
```

),

– Step 3: For each unique ID, combine all the sources that flagged it
aggregated AS (
SELECT
IDN_EON,
LISTAGG(source_table, ’, ’) WITHIN GROUP (ORDER BY source_table) AS DETECTION_TYPE
FROM all_ids
GROUP BY IDN_EON
),

– Step 4: Detect specific keywords and capabilities for each ID
keyword_detection AS (
SELECT
base_table.IDN_EON AS EON_ID,
MAX(t.TXT_DSPLY_LABEL) AS GRN,
MAX(NME_TAI_ASSET_DSPLY) AS APP_NAME,
a.detection_type AS DETECTION_TYPE,
‘YES’ AS ECOMMS_CAPABILITY,
MAX(t.TXT_RSRC_DESC) AS TXT_RSRC_DESC,
MAX(t.TXT_APPL_DESC) AS TXT_APPL_DESC,
CASE
WHEN MAX(w.Email) = ‘x’ THEN ‘YES’
WHEN MAX(TXT_RSRC_CAP_DESC) ILIKE ‘%b2b email%’ THEN ‘YES’
WHEN POSITION(‘mailing list’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘send email’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘over email’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘through emails’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘via email’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘bulk emails’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘email notifications’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘save-receipts’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘email to’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘send to’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘e-comm’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘e-comms’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘ecomm’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘ecomms’ IN MAX(t.TXT_RSRC_DESC)) > 0 THEN ‘YES’
WHEN POSITION(‘mailing list’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘Email’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘email’ IN d.TXT_DATA_LIFECYCL_MANG_ANSW) > 0 THEN ‘YES’
ELSE MAX(w.Email)
END AS EMAIL,
CASE
WHEN MAX(w.Comments) = ‘x’ THEN ‘YES’
WHEN POSITION(‘commentary’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘comment’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘Comments’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘comments’ IN MAX(t.TXT_RSRC_DESC)) > 0 THEN ‘YES’
ELSE MAX(w.Comments)
END AS COMMENTS,
CASE
WHEN MAX(w.Chat) = ‘x’ THEN ‘YES’
WHEN POSITION(‘live chat’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘Chat’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘chat’ IN MAX(t.TXT_RSRC_DESC)) > 0 THEN ‘YES’
ELSE MAX(w.Chat)
END AS CHAT,
CASE
WHEN MAX(w.SMS) = ‘x’ THEN ‘YES’
WHEN POSITION(‘through text messages’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘text messages’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘sms’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘via sms’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘text’ IN MAX(t.TXT_RSRC_DESC)) > 0 OR
POSITION(‘SMS’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 OR
POSITION(‘SMS’ IN MAX(t.TXT_RSRC_DESC)) > 0 THEN ‘YES’
ELSE MAX(w.SMS)
END AS SMS,
CASE
WHEN POSITION(‘Voice’ IN d.TXT_DATA_LIFECYCL_MANG_QSTN) > 0 THEN ‘YES’
ELSE ‘No’
END AS VOICE,
CASE
WHEN d.TXT_DATA_LIFECYCL_MANG_QSTN ILIKE ‘%Did LCD state that the communication feature was in-scope or out-of-scope for archiving?%’
AND d.TXT_DATA_LIFECYCL_MANG_ANSW ILIKE ‘%In scope%’ THEN ‘YES’
ELSE ‘No’
END AS IN_SCOPE_FOR_ARCHIVING
FROM base_table
LEFT JOIN aggregated a ON base_table.IDN_EON = a.IDN_EON
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_dlm_worm” w
ON base_table.IDN_EON = CAST(w.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_DLM_Plan_Responses_filtered2” d
ON base_table.IDN_EON = CAST(d.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_PrivacyQ_for_ITSO_Att_prepared_filtered_filtered” p
ON base_table.IDN_EON = CAST(p.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_MYSDM_Detections_for_Bulk_Email_prepared_filtered” m
ON base_table.IDN_EON = CAST(m.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_epr_filtered” e
ON base_table.IDN_EON = CAST(e.IDN_EON AS VARCHAR)
LEFT JOIN “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_ITAT_SYS_Active_Owning_Filter” t
ON base_table.IDN_EON = CAST(t.IDN_EON AS VARCHAR)
WHERE a.detection_type IS NOT NULL AND a.detection_type <> ‘ITAT-SYS’
GROUP BY base_table.IDN_EON, a.detection_type, d.TXT_DATA_LIFECYCL_MANG_ANSW, d.TXT_DATA_LIFECYCL_MANG_QSTN
),

– Step 5: Aggregate to one row per IDN_EON with merged values
final_output AS (
SELECT
EON_ID,
DETECTION_TYPE,
LISTAGG(DISTINCT NULLIF(GRN, ‘’), ’, ’) WITHIN GROUP (ORDER BY GRN) AS GRN,
LISTAGG(DISTINCT NULLIF(APP_NAME, ‘’), ’, ’) WITHIN GROUP (ORDER BY APP_NAME) AS APP_NAME,
MAX(ECOMMS_CAPABILITY) AS ECOMMS_CAPABILITY,
– If ‘YES’ exists anywhere, show ‘YES’; otherwise collect all distinct non-null values
CASE
WHEN LISTAGG(DISTINCT NULLIF(EMAIL, ‘’), ’, ’) WITHIN GROUP (ORDER BY EMAIL) LIKE ‘%YES%’ THEN ‘YES’
WHEN LISTAGG(DISTINCT NULLIF(EMAIL, ‘’), ’, ’) WITHIN GROUP (ORDER BY EMAIL) IS NOT NULL
THEN LISTAGG(DISTINCT NULLIF(EMAIL, ‘’), ’, ’) WITHIN GROUP (ORDER BY EMAIL)
ELSE NULL
END AS EMAIL,
CASE
WHEN LISTAGG(DISTINCT NULLIF(COMMENTS, ‘’), ’, ’) WITHIN GROUP (ORDER BY COMMENTS) LIKE ‘%YES%’ THEN ‘YES’
WHEN LISTAGG(DISTINCT NULLIF(COMMENTS, ‘’), ’, ’) WITHIN GROUP (ORDER BY COMMENTS) IS NOT NULL
THEN LISTAGG(DISTINCT NULLIF(COMMENTS, ‘’), ’, ’) WITHIN GROUP (ORDER BY COMMENTS)
ELSE NULL
END AS COMMENTS,
CASE
WHEN LISTAGG(DISTINCT NULLIF(CHAT, ‘’), ’, ’) WITHIN GROUP (ORDER BY CHAT) LIKE ‘%YES%’ THEN ‘YES’
WHEN LISTAGG(DISTINCT NULLIF(CHAT, ‘’), ’, ’) WITHIN GROUP (ORDER BY CHAT) IS NOT NULL
THEN LISTAGG(DISTINCT NULLIF(CHAT, ‘’), ’, ’) WITHIN GROUP (ORDER BY CHAT)
ELSE NULL
END AS CHAT,
CASE
WHEN LISTAGG(DISTINCT NULLIF(SMS, ‘’), ’, ’) WITHIN GROUP (ORDER BY SMS) LIKE ‘%YES%’ THEN ‘YES’
WHEN LISTAGG(DISTINCT NULLIF(SMS, ‘’), ’, ’) WITHIN GROUP (ORDER BY SMS) IS NOT NULL
THEN LISTAGG(DISTINCT NULLIF(SMS, ‘’), ’, ’) WITHIN GROUP (ORDER BY SMS)
ELSE NULL
END AS SMS,
CASE
WHEN LISTAGG(DISTINCT NULLIF(VOICE, ‘’), ’, ’) WITHIN GROUP (ORDER BY VOICE) LIKE ‘%YES%’ THEN ‘YES’
WHEN LISTAGG(DISTINCT NULLIF(VOICE, ‘’), ’, ’) WITHIN GROUP (ORDER BY VOICE) IS NOT NULL
THEN LISTAGG(DISTINCT NULLIF(VOICE, ‘’), ’, ’) WITHIN GROUP (ORDER BY VOICE)
ELSE NULL
END AS VOICE,
CASE
WHEN LISTAGG(DISTINCT NULLIF(IN_SCOPE_FOR_ARCHIVING, ‘’), ’, ’) WITHIN GROUP (ORDER BY IN_SCOPE_FOR_ARCHIVING) LIKE ‘%YES%’ THEN ‘YES’
WHEN LISTAGG(DISTINCT NULLIF(IN_SCOPE_FOR_ARCHIVING, ‘’), ’, ’) WITHIN GROUP (ORDER BY IN_SCOPE_FOR_ARCHIVING) IS NOT NULL
THEN LISTAGG(DISTINCT NULLIF(IN_SCOPE_FOR_ARCHIVING, ‘’), ’, ’) WITHIN GROUP (ORDER BY IN_SCOPE_FOR_ARCHIVING)
ELSE ‘No’
END AS IN_SCOPE_FOR_ARCHIVING
FROM keyword_detection
GROUP BY EON_ID, DETECTION_TYPE
)

– Step 6: Add the ONBOARDED_TO_ECOMMS_ARCHIVE column based on risk B table
SELECT
EON_ID,
DETECTION_TYPE,
GRN,
APP_NAME,
ECOMMS_CAPABILITY,
EMAIL,
COMMENTS,
CHAT,
SMS,
VOICE,
IN_SCOPE_FOR_ARCHIVING,
CASE
WHEN NOT EXISTS (
SELECT 1
FROM “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_Risk_B_Output_2_prepared” risk_b
WHERE risk_b.IDN_EON = final_output.EON_ID
) THEN
CASE
WHEN LOWER(DETECTION_TYPE) NOT LIKE ‘%dlm_plan_responses%’ THEN ‘A,B’
ELSE ‘B’
END
ELSE
CASE
WHEN LOWER(DETECTION_TYPE) NOT LIKE ‘%dlm_plan_responses%’ THEN ‘A’
ELSE NULL
END
END AS SUB_RISK,
CASE
WHEN EXISTS (
SELECT 1
FROM “LH_SND_DB”.“WMCLOUD_PRJ166”.“MAEVEPERSONAL_Risk_B_Output_2_prepared” risk_b
WHERE risk_b.IDN_EON = final_output.EON_ID
) THEN ‘YES’
ELSE ‘No’
END AS ONBOARDED_TO_ECOMMS_ARCHIVE
FROM final_output
ORDER BY EON_ID;